stack = [] 
stack.append('One')
stack.append('Two')
stack.append('Three') 
print('Initial stack')
print(stack)
print('\nElements popped from stack:')
print(stack.pop())
print(stack.pop())
print(stack.pop())
print('\nStack after elements are popped:')
print(stack)